- id: jsonnet-format
  name: jsonnetfmt
  description: Automatically format jsonnet files.
  entry: jsonnetfmt
  args: [-i]
  language: golang
<<<<<<< HEAD
  files: '\.(jsonnet|libsonnet)$'
  additional_dependencies: [ "github.com/nbycomp/go-jsonnet/cmd/jsonnetfmt" ]
=======
  files: \.(jsonnet|libsonnet)$
  minimum_pre_commit_version: 2.10.1
- id: jsonnet-lint
  name: jsonnet-lint
  description: Lint jsonnet files.
  entry: jsonnet-lint
  language: golang
  files: \.(jsonnet|libsonnet)$
  minimum_pre_commit_version: 2.10.1
>>>>>>> ece9c5dc949f90c5f6f5f84e34a32234b4b91c5e
